### ISSUE TITLE
3.0 plan

### ISSUE THREAD

**Issue by azu** [proofdict/proofdict#22]
It is next major update.

## Tasks

- [ ] Deprecate tag "noun" special behavior #21 
- [x] textlint rename blacklistTags -> denyTags, whitelistTags -> alllowTags #12 #25
- [x] Import editor that change editor's URL #18

**Comment by azu** [comment]
https://github.com/proofdict/proofdict/blob/master/CHANGELOG.md#300-2018-11-17
Release

We want to write release note.

**Comment by azu** [comment]
Need to improve documents.
